FROM ubuntu

USER root

RUN \
  apt-get update && \
  apt-get install -y software-properties-common && \
  apt-add-repository ppa:ansible/ansible && \
  apt-get update && \
  apt-get install -y --force-yes ansible

COPY ansible.cfg /etc/ansible/ansible.cfg

RUN mkdir /ansible
WORKDIR /ansible